# Generated by Django 5.2.1 on 2025-05-26 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelTable(
            name='post',
            table='testing_posts',
        ),
    ]
