# Generated by Django 5.2.1 on 2025-05-26 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0002_alter_post_options_alter_post_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='post',
            table='testingsssssss_posts',
        ),
    ]
