# Generated by Django 5.2.1 on 2025-05-26 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0003_alter_post_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-created_at'], 'verbose_name': 'Blog Post', 'verbose_name_plural': 'Blog Posts'},
        ),
        migrations.AlterUniqueTogether(
            name='post',
            unique_together={('title', 'user_email')},
        ),
    ]
